### ISSUE TITLE
Unraid Installation

### ISSUE THREAD

**Issue by BeardedTek** [BeardedTek-com/fEVR#45]
### Discussed in https://github.com/BeardedTek-com/fEVR/discussions/44

<div type='discussions-op-text'>

<sup>Originally posted by **DrSpaldo** April  1, 2022</sup>
I would like to have a look at the project and was wondering if you had a suggested method of installation on a machine running Unraid?</div>

**Comment by markmghali** [comment]
yes please an unraid template would be amazing! Project looks great!

**Comment by Mikhail5555** [comment]
If someone could try importing the following template and testing if I didn't forget any values/default values set somewhat correct that would be great.
P.s. add it to the `/boot/config/plugins/dockerMan/templates-user` folder as `my-fEVR.xml` on your unRaid install.

```xml
<?xml version="1.0"?>
<Container version="2">
  <Name>fEVR</Name>
  <Repository>ghcr.io/beardedtek-com/fevr:main</Repository>
  <Registry>https://github.com/BeardedTek-com/fEVR/pkgs/container/fevr</Registry>
  <Network>bridge</Network>
  <Shell>sh</Shell>
  <Privileged>false</Privileged>
  <Project>https://github.com/BeardedTek-com/fEVR</Project>
  <Overview>fEVR works along side of frigate and home assistant to collect video and snapshots of objects detected using your existing camera systems.</Overview>
  <Category>HomeAutomation: Security:</Category>
  <WebUI>http://[IP]:[PORT:5080]/</WebUI>
  <Description>fEVR works along side of frigate and home assistant to collect video and snapshots of objects detected using your existing camera systems.</Description>
  <Config Name="WebUI" Target="5080" Default="" Mode="tcp" Description="Container Port: 5080" Type="Port" Display="always" Required="false" Mask="false"/>
  <Config Name="MQTT_PASS" Target="MQTT_PASS" Default="" Mode="" Description="Container Variable: MQTT_PASS" Type="Variable" Display="always" Required="false" Mask="false"/>
  <Config Name="MQTT_USER" Target="MQTT_USER" Default="" Mode="" Description="Container Path: MQTT_USER" Type="Variable" Display="always" Required="false" Mask="false"/>
  <Config Name="MQTT_BROKER_PORT" Target="MQTT_BROKER_PORT" Default="1883" Mode="" Description="Container Variable: MQTT_BROKER_PORT" Type="Variable" Display="always" Required="true" Mask="false">1883</Config>
  <Config Name="MQTT_BROKER_URL" Target="MQTT_BROKER_URL" Default="" Mode="" Description="Container Variable: MQTT_BROKER_URL" Type="Variable" Display="always" Required="true" Mask="false"/>
  <Config Name="FRIGATE_URL" Target="FRIGATE_URL" Default="http://frigate:5000" Mode="" Description="Container Variable: FRIGATE_URL" Type="Variable" Display="always" Required="true" Mask="false">http://frigate:5000</Config>
  <Config Name="Data" Target="/var/www/data   " Default="/mnt/user/appdata/fevr/data" Mode="rw" Description="Contains the SQLite database and config.json files" Type="Path" Display="always" Required="false" Mask="false">/mnt/user/appdata/fevr/data</Config>
  <Config Name="Events" Target="/var/www/html/events" Default="/mnt/user/appdata/fevr/events" Mode="rw" Description=" Save events to a local folder" Type="Path" Display="always" Required="false" Mask="false">/mnt/user/appdata/fevr/events</Config>
  <Config Name="MQTT_TOPICS" Target="MQTT_TOPICS" Default="frigate/+" Mode="" Description="Container Variable: MQTT_TOPICS" Type="Variable" Display="advanced" Required="false" Mask="false">frigate/+</Config>
  <Config Name="FEVR_IP" Target="FEVR_IP" Default="0.0.0.0" Mode="" Description="Container Variable: FEVR_IP" Type="Variable" Display="advanced" Required="true" Mask="false">0.0.0.0</Config>
  <Config Name="FEVR_PORT" Target="FEVR_PORT" Default="5080" Mode="" Description="Container Variable: FEVR_PORT" Type="Variable" Display="advanced" Required="true" Mask="false">5080</Config>
  <Config Name="FEVR_DEBUG" Target="FEVR_DEBUG" Default="false" Mode="" Description="Container Variable: FEVR_DEBUG" Type="Variable" Display="advanced" Required="false" Mask="false">false</Config>
  <Config Name="PUID" Target="PUID" Default="99" Mode="" Description="Container Variable: PUID" Type="Variable" Display="advanced-hide" Required="false" Mask="false">99</Config>
  <Config Name="PGID" Target="PGID" Default="100" Mode="" Description="Container Variable: PGID" Type="Variable" Display="advanced-hide" Required="false" Mask="false">100</Config>
</Container>
```

**Comment by BeardedTek** [comment]
Okay, the container comes up, but I cannot reach <unRAID_IP>:5080

**Comment by Mikhail5555** [comment]
Can you verify that `WebUI` has port 5080 set? (It has no default value because some people exclusively run it behind an reverse proxy and then default values are annoying)

**Comment by BeardedTek** [comment]
Yeah I'm dumb.  I literally just saw that.

Well, at least I'm learning a new environment.

**Comment by Mikhail5555** [comment]
Haha cool that you actually installed Unraid to try this ;)

**Comment by BeardedTek** [comment]
Okay Awesome!  I need to adjust some scripting, but it will actually improve all versions so that's a good thing.

**Comment by BeardedTek** [comment]
Well if I'm going to support it I need to understand it somewhat.  It was easier than I thought.  And now I have an easy way to test.

**Comment by BeardedTek** [comment]
Added [Beardedtek-com/unraid-templates](https://github.com/beardedtek-com/unraid-templates) repository to easily add this to your unraid setup.

Simply add https://github.com/beardedtek-com/unraid-templates to your template repositories on the docker tab of unraid (6.9.2 tested)

![unraidTemplates](https://user-images.githubusercontent.com/93575915/161844887-faa715a9-60cb-4003-a35d-b07bda2a7c28.png)

**Comment by markmghali** [comment]
amazing! will test and report back.

**Comment by markmghali** [comment]
doesn't looks like it's populating properly for me?


![image](https://user-images.githubusercontent.com/17356528/161845741-d4091df5-1af7-4d3f-92ea-0a981c63cb0f.png)

**Comment by BeardedTek** [comment]
Leaving this open as currently the following must be done once the container is up:

- Open console and run this bash script:
```
#!/bin/sh
mkdir /var/www/data
mkdir /var/www/data/db
mkdir /var/www/data/config
wget -O /var/www/data/db/fEVR.sqlite https://raw.githubusercontent.com/BeardedTek-com/fEVR/main/docker/fEVR/rootfs/var/www/data/db/fEVR.sqlite
wget -O /var/www/data/config/config.json https://raw.githubusercontent.com/BeardedTek-com/fEVR/main/docker/fEVR/rootfs/var/www/data/config/config.json
```

**Comment by BeardedTek** [comment]
> doesn't looks like it's populating properly for me?
> 
> ![image](https://user-images.githubusercontent.com/17356528/161845741-d4091df5-1af7-4d3f-92ea-0a981c63cb0f.png)

Give me 2 minutes and I'll fix the typo

**Comment by BeardedTek** [comment]
Okay, all set.  I forgot a > at the end of the </Repository> tag

**Comment by BeardedTek** [comment]
Make sure to open a console and run that script I posted 

> Leaving this open as currently the following must be done once the container is up:
> 
> * Open console and run this bash script:
> 
> ```
> #!/bin/sh
> mkdir /var/www/data
> mkdir /var/www/data/db
> mkdir /var/www/data/config
> wget -O /var/www/data/db/fEVR.sqlite https://raw.githubusercontent.com/BeardedTek-com/fEVR/main/docker/fEVR/rootfs/var/www/data/db/fEVR.sqlite
> wget -O /var/www/data/config/config.json https://raw.githubusercontent.com/BeardedTek-com/fEVR/main/docker/fEVR/rootfs/var/www/data/config/config.json
> ```

**Comment by markmghali** [comment]
Awesome! working properly now

![image](https://user-images.githubusercontent.com/17356528/161846337-04349cc9-ca44-4d44-a2bf-0dcbf381c3dc.png)

**Comment by Mikhail5555** [comment]
> Leaving this open as currently the following must be done once the container is up:
> 
> * Open console and run this bash script:
> 
> ```
> #!/bin/sh
> mkdir /var/www/data
> mkdir /var/www/data/db
> mkdir /var/www/data/config
> wget -O /var/www/data/db/fEVR.sqlite https://raw.githubusercontent.com/BeardedTek-com/fEVR/main/docker/fEVR/rootfs/var/www/data/db/fEVR.sqlite
> wget -O /var/www/data/config/config.json https://raw.githubusercontent.com/BeardedTek-com/fEVR/main/docker/fEVR/rootfs/var/www/data/config/config.json
> ```

You could also add the config.json & fEVR.sqlite to the appdata folder in unraid:
```
wget -O /mnt/user/appdata/fevr/data/fEVR.sqlite https://raw.githubusercontent.com/BeardedTek-com/fEVR/main/docker/fEVR/rootfs/var/www/data/db/fEVR.sqlite
wget -O /mnt/user/appdata/fevr/data/config.json https://raw.githubusercontent.com/BeardedTek-com/fEVR/main/docker/fEVR/rootfs/var/www/data/config/config.json
```

**Comment by BeardedTek** [comment]
Changes integrated into docker container.  Building and testing now

**Comment by BeardedTek** [comment]
Okay, had to revert the changes in the main branch.  I'll have another set up updates tomorrow.  For now, if you run that script above, it *should* work.

**Comment by markmghali** [comment]
tried running this on unraid today. It is not starting up properly. unable to access the sqllite DB I think.

here are the logs:

ErrorWarningSystemArrayLogin


conn = sqlite3.connect(self.database, timeout=self._timeout,
sqlite3.OperationalError: unable to open database file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/bin/sqlite_web", line 33, in <module>
sys.exit(load_entry_point('sqlite-web==0.4.0', 'console_scripts', 'sqlite_web')())
File "/usr/lib/python3.9/site-packages/sqlite_web/sqlite_web.py", line 870, in main
initialize_app(args[0], options.read_only, password, options.url_prefix,
File "/usr/lib/python3.9/site-packages/sqlite_web/sqlite_web.py", line 837, in initialize_app
dataset = SqliteDataSet('sqlite:///%s' % filename, bare_fields=True)
File "/usr/lib/python3.9/site-packages/playhouse/dataset.py", line 44, in __init__
self._database.connect(reuse_if_open=True)
File "/usr/lib/python3.9/site-packages/peewee.py", line 3116, in connect
self._initialize_connection(self._state.conn)
File "/usr/lib/python3.9/site-packages/peewee.py", line 2950, in __exit__
reraise(new_type, new_type(exc_value, *exc_args), traceback)
File "/usr/lib/python3.9/site-packages/peewee.py", line 191, in reraise
raise value.with_traceback(tb)
File "/usr/lib/python3.9/site-packages/peewee.py", line 3113, in connect
self._state.set_connection(self._connect())
File "/usr/lib/python3.9/site-packages/peewee.py", line 3453, in _connect
conn = sqlite3.connect(self.database, timeout=self._timeout,
peewee.OperationalError: unable to open database file
sqlite_web running on port .


Starting sqlite web at http://172.17.0.23:5081


Traceback (most recent call last):
File "/usr/lib/python3.9/site-packages/peewee.py", line 3113, in connect
self._state.set_connection(self._connect())
File "/usr/lib/python3.9/site-packages/peewee.py", line 3453, in _connect
conn = sqlite3.connect(self.database, timeout=self._timeout,
sqlite3.OperationalError: unable to open database file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/bin/sqlite_web", line 33, in <module>
sys.exit(load_entry_point('sqlite-web==0.4.0', 'console_scripts', 'sqlite_web')())
File "/usr/lib/python3.9/site-packages/sqlite_web/sqlite_web.py", line 870, in main
initialize_app(args[0], options.read_only, password, options.url_prefix,
File "/usr/lib/python3.9/site-packages/sqlite_web/sqlite_web.py", line 837, in initialize_app
dataset = SqliteDataSet('sqlite:///%s' % filename, bare_fields=True)
File "/usr/lib/python3.9/site-packages/playhouse/dataset.py", line 44, in __init__
self._database.connect(reuse_if_open=True)
File "/usr/lib/python3.9/site-packages/peewee.py", line 3116, in connect
self._initialize_connection(self._state.conn)
File "/usr/lib/python3.9/site-packages/peewee.py", line 2950, in __exit__
reraise(new_type, new_type(exc_value, *exc_args), traceback)
File "/usr/lib/python3.9/site-packages/peewee.py", line 191, in reraise
raise value.with_traceback(tb)
File "/usr/lib/python3.9/site-packages/peewee.py", line 3113, in connect
self._state.set_connection(self._connect())
File "/usr/lib/python3.9/site-packages/peewee.py", line 3453, in _connect
conn = sqlite3.connect(self.database, timeout=self._timeout,
peewee.OperationalError: unable to open database file
sqlite_web running on port .


Starting sqlite web at http://172.17.0.23:5081


Traceback (most recent call last):
File "/usr/lib/python3.9/site-packages/peewee.py", line 3113, in connect
self._state.set_connection(self._connect())
File "/usr/lib/python3.9/site-packages/peewee.py", line 3453, in _connect
conn = sqlite3.connect(self.database, timeout=self._timeout,
sqlite3.OperationalError: unable to open database file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/bin/sqlite_web", line 33, in <module>
sys.exit(load_entry_point('sqlite-web==0.4.0', 'console_scripts', 'sqlite_web')())
File "/usr/lib/python3.9/site-packages/sqlite_web/sqlite_web.py", line 870, in main
initialize_app(args[0], options.read_only, password, options.url_prefix,
File "/usr/lib/python3.9/site-packages/sqlite_web/sqlite_web.py", line 837, in initialize_app
dataset = SqliteDataSet('sqlite:///%s' % filename, bare_fields=True)
File "/usr/lib/python3.9/site-packages/playhouse/dataset.py", line 44, in __init__
self._database.connect(reuse_if_open=True)
File "/usr/lib/python3.9/site-packages/peewee.py", line 3116, in connect
self._initialize_connection(self._state.conn)
File "/usr/lib/python3.9/site-packages/peewee.py", line 2950, in __exit__
reraise(new_type, new_type(exc_value, *exc_args), traceback)
File "/usr/lib/python3.9/site-packages/peewee.py", line 191, in reraise
raise value.with_traceback(tb)
File "/usr/lib/python3.9/site-packages/peewee.py", line 3113, in connect
self._state.set_connection(self._connect())
File "/usr/lib/python3.9/site-packages/peewee.py", line 3453, in _connect
conn = sqlite3.connect(self.database, timeout=self._timeout,
peewee.OperationalError: unable to open database file
sqlite_web running on port .

**Comment by Mikhail5555** [comment]
@markmghali have you performed the steps 3 comments above yours?

**Comment by markmghali** [comment]
> @markmghali have you performed the steps 3 comments above yours?

duh thank you! running it in the console of the docker container worked! Thank you again

**Comment by BeardedTek** [comment]
This version of fEVR was built docker first and assumes a docker environment and does not set the proper permissions on initial startup.

v0.6 is currently under development and will fix this issue.

**Comment by markmghali** [comment]
Next question I have put my frigate IP in the frigate url field and in the webui it is stating it cannot connect to frigate.local:5000

see screenshots

![image](https://user-images.githubusercontent.com/17356528/163257227-42b06649-3446-4ff4-b8ec-35c97afc1450.png)


webui

![image](https://user-images.githubusercontent.com/17356528/163257312-b253f004-a490-444d-a712-0e01797dc039.png)

**Comment by BeardedTek** [comment]
I'll have to dive into this one but again due to the docker-centric approach I was taking previous to the 0.6 branch, it must be edited while the container is running for the first time.  Edit /var/www/data/config/config.json to reflect your settings.

I don't plan to fix this af 0.6 is a major rewrite that will completely negate this process.

I'd highly recommend installing via docker-compose until the rewrites are complete.

**Comment by markmghali** [comment]
> I'll have to dive into this one but again due to the docker-centric approach I was taking previous to the 0.6 branch, it must be edited while the container is running for the first time. Edit /var/www/data/config/config.json to reflect your settings.
> 
> I don't plan to fix this af 0.6 is a major rewrite that will completely negate this process.
> 
> I'd highly recommend installing via docker-compose until the rewrites are complete.

Sounds Good! I will eagerly await the next release! Thank you again for all your work!

**Comment by BeardedTek** [comment]
fEVR v0.6 Release Candidate Released!
frigate Event Video Recorder version 0.6 Release Candidate has been released today, completely rewritten in Flask with full WebUI setup and a new database subsystem.
https://github.com/beardedtek-com/fevr/tree/v0.6

https://github.com/BeardedTek-com/fEVR/releases/tag/v0.6-RC

https://twitter.com/BeardedTek/status/1519715631259471872?t=DgukPY4wwk7OoCtIdFspzQ&s=19

**Comment by BeardedTek** [comment]
This unRAID template is available at:
https://github.com/BeardedTek-com/unraid-templates


<?xml version="1.0"?>
<Container version="2">
  <Date>2022-04-18</Date>
  <Beta>True</Beta>
  <Name>fEVR</Name>
  <Repository>ghcr.io/beardedtek-com/fevr-flask:main</Repository>
  <Registry>https://github.com/BeardedTek-com/fEVR/pkgs/container/fevr</Registry>
  <Repository>beardedtek-com/fEVR-flask</Repository>
  <Project>https://fevr.video</Project>
  <Support>https://github.com/beardedtek-com/fEVR/discussions</Support>
  <Overview>fEVR works along side of frigate and home assistant to collect video and snapshots of objects detected using your existing camera systems.</Overview>
  <Category>HomeAutomation: Security:</Category>
  <Shell>bash</Shell>
  <Privileged>false</Privileged>
  <Network>bridge</Network>
  <WebUI>http://[IP]:[PORT:5090]/</WebUI>
  <Icon>https://fevr.video/img/logo.svg</Icon>
  <Description>fEVR works along side of frigate and home assistant to collect video and snapshots of objects detected using your existing camera systems.</Description>

  <Config Name="MQTT_CLIENT"
    Description="Runs fEVR mqtt client on the same docker container"
    Target="MQTT_CLIENT" Default="" Mode="" Type="Variable"
    Display="always" Required="true" Mask="false">true
  </Config>

  <Config Name="WebUI" 
    Description="Container Port: 5090"
    Target="5090" Default="" Mode="tcp" Type="Port"
    Display="always" Required="false" Mask="false"
  />

  <Config Name="PUID"
    Description="Container Variable: PUID"
    Target="PUID" Default="1000" Mode="" Type="Variable"
    Display="advanced-hide" Required="false" Mask="false">1000
  </Config>

  <Config Name="PGID"
    Description="Container Variable: PGID"
    Target="PGID" Default="1000" Mode="" Type="Variable"
    Display="advanced-hide" Required="false" Mask="false">1000
  </Config>

  <Config Name="Events"
    Target="/fevr/app/static/events"
    Default="/mnt/user/appdata/fevr/events" Mode="rw"
    Description=" Save events to a local folder" 
    Type="Path" Display="always" Required="false"
    Mask="false">/mnt/user/appdata/fevr/events
  </Config>

  <Config Name="FEVR_PORT"
    Description="Container Variable: FEVR_PORT"
    Target="FEVR_PORT" Default="5080" Mode="" Type="Variable"
    Display="advanced" Required="true" Mask="false">5090
  </Config>

  <Config Name="FLASK_ENV"
    Description="Set to 'development' for debug mode"
    Target="FLASK_ENV" Default="" Mode="" Type="Variable"
    Display="advanced" Required="false" Mask="false">
  </Config>

</Container>

**Comment by DrSpaldo** [comment]
I can't get the RC or normal version to load. Doesn't even produce a log. Normal version at least populates the docker questions, but the RC version doesn't. I will keep trying stuff, I can't run those commands above in the docker console as it never loads the docker to press the console

**Comment by DrSpaldo** [comment]
Is anyone who has been able to get it to work able to post how they configured it? Ie. The IP (docker internal, LAN, etc). Bridge, host, custom net

**Comment by rickydg** [comment]
Having the same issue as @DrSpaldo 

Cannot get the container to start, have tried fevr and fevr-flask. Have set network to bridge, host and br0. No joy.

**Comment by DrSpaldo** [comment]
> Having the same issue as @DrSpaldo
> 
> Cannot get the container to start, have tried fevr and fevr-flask. Have set network to bridge, host and br0. No joy.

Hopefully someone gets it going, I’ve given up for the time being

**Comment by BeardedTek** [comment]
I have decided that until testing is complete on v0.6 I am halting unRAID releases.  If someone would like to explore packaging this up for unRAID, you are more than welcome.  This repository will be for the application and docker ONLY.

I am transferring this issue to my unraid templates repository as this is out of the scope of this repository.
